name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "2.4.1"
          args: --check lua/ tests/

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - uses: jdx/mise-action@v4
      - name: Typecheck
        run: make typecheck

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim_version: ["stable", "nightly"]
    steps:
      - uses: actions/checkout@v7
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - name: Install luarocks
        run: sudo apt-get update && sudo apt-get install -y luarocks
      - name: Run tests
        run: nvim -l tests/minit.lua --minitest
